import {comp} from "./types";
import {overload} from "./core";
import * as pl from "./pipelines";
import * as p  from "./protocols";
import * as a from "./associatives";
import * as t from "./transducers";
import * as s from "./sequences";
export * from "./core";
export * from "./protocol";
export * from "./protocols";
export * from "./types";
export * from "./predicates";
export * from "./sequences";
export * from "./associatives";
export * from "./pipelines";
export * from "./signals";
export * from "./dom";
export const second = comp(p.first, p.next);