import * as core from './core';
import * as coll from './coll';
import * as protocol from './protocol';
import * as el from './types/html-element';
import {curry, flip} from './core';
export {curry, flip} from './core';
export {chain} from './core';
export {remove, text, show, hide} from './types/html-element';
export const arity     = curry(core.arity);
export const eq        = curry(core.eq);
export const ne        = curry(core.ne);
export const lt        = flip(core.lt);
export const lte       = flip(core.lte);
export const gt        = flip(core.gt);
export const gte       = flip(core.gte);
export const tap       = curry(core.tap);
export const add       = curry(core.add);
export const subtract  = flip(core.subtract);
export const satisfies = curry(protocol.satisfies);
export const each      = flip(coll.each);
export const map       = flip(coll.map);
export const filter    = flip(coll.filter);
export const reject    = flip(coll.reject);
export const find      = flip(coll.find);
export const style     = flip(el.style, 3);
export const hasClass  = flip(el.hasClass, 2);
export const addClass  = flip(el.addClass, 2);
export const setClass  = flip(el.setClass, 3);
export const removeClass = flip(el.removeClass, 2);
export const toggleClass = flip(el.toggleClass, 2);
export const inc       = add(+1);
export const dec       = add(-1);