import {curry} from "./types";
import {overload, subj, obj} from "./core";
import * as c from "./core";
import * as p from "./protocols";
import * as a from "./associatives";
import * as dom from "./dom";
import * as pred from "./predicates";
import * as T from "./types";

export * from "./core";
export * from "./protocols";
export * from "./types";
export * from "./pipelines";
export * from "./dom";
export {someFn} from "./predicates";

export const reduce = curry(p.reduce, 3);
export const append = subj(p.append);
export const prepend = subj(p.prepend);
export const conj = subj(p.conj);
export const invoke = subj(p.invoke);
export const find = subj(p.find);
export const assoc = subj(p.assoc);
export const contains = subj(p.contains);
export const dissoc = subj(p.dissoc);
export const pub = subj(p.pub);
export const sub = subj(p.sub);
export const superset = subj(p.superset);
export const doto = subj(c.doto);
export const transduce = obj(T.transduce);
export const each = obj(T.each);
export const dorun = obj(T.dorun);
export const doall = obj(T.doall);
export const dotimes = obj(T.dotimes);
export const some = obj(T.some);
export const notSome = obj(T.notSome);
export const notAny = obj(T.notAny);
export const every = obj(T.every);
export const notEvery = obj(T.notEvery);
export const map = obj(T.map);
export const mapa = obj(T.mapa);
export const mapIndexed = obj(T.mapIndexed);
export const keepIndexed = obj(T.keepIndexed);
export const filter = obj(T.filter);
export const filtera = obj(T.filtera);
export const remove = obj(T.remove);
export const keep = obj(T.keep);
export const drop = obj(T.drop);
export const dropWhile = obj(T.dropWhile);
export const dropLast = obj(T.dropLast);
export const take = obj(T.take);
export const takeWhile = obj(T.takeWhile);
export const takeNth = obj(T.takeNth);
export const takeLast = obj(T.takeLast);
export const interleave = obj(T.interleave);
export const interpose = obj(T.interpose);
export const partition = obj(T.partition);
export const partitionAll = obj(T.partitionAll);
export const partitionBy = obj(T.partitionBy);
export const splitAt = obj(T.splitAt);
export const splitWith = obj(T.splitWith);
export const mapcat = obj(T.mapcat);
export const sort = obj(T.sort);
export const sortBy = obj(T.sortBy);
export const groupInto = obj(T.groupInto);
export const groupBy = obj(T.groupBy);
export const doseq = obj(T.doseq);
export const detect = obj(T.detect);
export const repeatedly = obj(T.repeatedly);
export const repeat = obj(T.repeat);
export const interate = obj(T.interate);
export const best = obj(T.best);
export const scan = obj(T.scan);
export const andSelf = obj(T.andSelf);
export const sel = obj(T.sel);
export const into = obj(T.into);
export const isInstance = subj(c.isInstance);
export const pre = subj(pred.pre);
export const post = subj(pred.post);
export const matches = subj(pred.matches);
export const branch = obj(pred.branch);
export const cond = subj(pred.cond);
export const everyPair = obj(pred.everyPair);
export const compare = subj(pred.compare);
export const isIdentical = subj(pred.isIdentical);
export const gt = subj(pred.gt);
export const gte = subj(pred.gte);
export const lt = subj(pred.lt);
export const lte = subj(pred.lte);
export const eq = subj(pred.eq);
export const notEq = subj(pred.notEq);
export const equal = subj(pred.equal);
export const min = subj(pred.min);
export const max = subj(pred.max);
export const get = subj(a.get);
export const getIn = subj(a.getIn);
export const index = obj(a.get);
export const assocIn = subj(a.assocIn);
export const update = subj(a.update);
export const clamp = subj(T.clamp);
export const matches = subj(dom.matches);
export const embeds = subj(p.embeds);
export const embed = subj(p.embed);